# Generated by Django 4.1.1 on 2022-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                ("valid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Proxies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("date_joind", models.DateField(auto_now_add=True)),
                ("usename", models.CharField(max_length=255)),
                ("passwd", models.CharField(max_length=255)),
                ("expiry", models.DateField()),
            ],
        ),
    ]
