# Generated by Django 4.1.1 on 2022-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("passwd", models.CharField(max_length=255)),
            ],
        ),
    ]
