# Generated by Django 4.1.1 on 2022-09-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_proxies_delete_userr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("passwd", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Userr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("date_joind", models.DateField(auto_now_add=True)),
                ("usename", models.CharField(max_length=255)),
                ("passwd", models.CharField(max_length=255)),
                ("expiry", models.DateField()),
            ],
        ),
    ]
