# Generated by Django 4.1.3 on 2022-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proxies_userr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userr',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='userr',
            name='number',
        ),
        migrations.RemoveField(
            model_name='userr',
            name='passwd',
        ),
        migrations.AddField(
            model_name='userr',
            name='address',
            field=models.CharField(default='0x00000000000000000000000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='userr',
            name='email',
            field=models.CharField(default='examp@ex.com', max_length=255),
        ),
    ]
