# Generated by Django 4.1.3 on 2022-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_items_delete_emails_delete_proxies'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='chain',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
