# Generated by Django 4.1.3 on 2022-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_items_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='chain',
            field=models.IntegerField(default=1, max_length=255),
        ),
    ]
