# Generated by Django 4.1.3 on 2022-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_items_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='owner',
            field=models.CharField(default='0x000000000000000000000000000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='userr',
            name='address',
            field=models.CharField(default='0x000000000000000000000000000000', max_length=255),
        ),
    ]
