# Generated by Django 4.1.3 on 2022-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_items_owner_alter_userr_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='cover',
            field=models.CharField(default='https://i.imgur.com/jxyuizJ.jpeg', max_length=255),
        ),
        migrations.AddField(
            model_name='userr',
            name='profile',
            field=models.CharField(default='https://i.imgur.com/KykRUCV.jpeg', max_length=255),
        ),
    ]
