# Generated by Django 4.1.3 on 2022-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userr_cover_userr_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(default='0x000000000000000000000000000000', max_length=255)),
                ('amount', models.CharField(default='examp@ex.com', max_length=255)),
                ('date_joind', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='tokenIds',
            field=models.IntegerField(default=1),
        ),
    ]
