# Generated by Django 4.1.3 on 2022-12-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bids_items_tokenids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='tokenIds',
            new_name='tokenId',
        ),
    ]
