# Generated by Django 4.1.3 on 2022-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_tokenids_items_tokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='license',
            field=models.BooleanField(default=False),
        ),
    ]
