# Generated by Django 4.1.3 on 2022-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_items_auction_items_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='contract_address',
            field=models.CharField(default='0x000000000000000000000000000000', max_length=255),
        ),
    ]
