# Generated by Django 4.1.3 on 2022-12-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bids_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='chainId',
            field=models.IntegerField(default=0),
        ),
    ]
