# Generated by Django 4.1.3 on 2022-12-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_userr_facebook_userr_instagram_userr_twiter"),
    ]

    operations = [
        migrations.CreateModel(
            name="collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        default="0x000000000000000000000000000000", max_length=255
                    ),
                ),
                ("name", models.IntegerField(default=0)),
                ("chainId", models.IntegerField(default=0)),
                ("date_joind", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userr",
            name="address",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255, unique=True
            ),
        ),
    ]
