# Generated by Django 4.1.3 on 2022-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_collection_avatr_collection_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="contract",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255
            ),
        ),
    ]
