# Generated by Django 4.1.3 on 2023-01-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_collection_description_alter_collection_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answere", models.TextField()),
            ],
        ),
    ]
