# Generated by Django 4.1.3 on 2023-01-18 02:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answere",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
