# Generated by Django 4.1.3 on 2023-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_question_answere"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.CharField(
                        default="0x000000000000000000000000000000", max_length=255
                    ),
                ),
                (
                    "contract",
                    models.CharField(
                        default="0x000000000000000000000000000000", max_length=255
                    ),
                ),
                (
                    "description",
                    models.CharField(default="description", max_length=255),
                ),
                ("chainId", models.IntegerField(default=0)),
                ("claimed", models.BooleanField(default=False)),
                ("avatr", models.CharField(default="not", max_length=255)),
                ("date_joind", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
