# Generated by Django 4.1.3 on 2023-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_reward_rewardid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.CharField(max_length=255)),
                ("long", models.CharField(max_length=255)),
            ],
        ),
    ]
