# Generated by Django 4.1.3 on 2023-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(default="description"),
        ),
    ]
