# Generated by Django 4.1.3 on 2023-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_collection_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="contract",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255, unique=True
            ),
        ),
    ]
