# Generated by Django 4.1.3 on 2023-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_collection_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="contract",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255
            ),
        ),
    ]
