# Generated by Django 4.1.3 on 2023-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_collection_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apply", models.BooleanField(default=False)),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                ("paid", models.BooleanField(default=False)),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="collection",
            name="banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userr",
            name="banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userr",
            name="fee_discount",
            field=models.BooleanField(default=False),
        ),
    ]
