# Generated by Django 4.1.3 on 2023-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_bidunlist_bidid_bidunlist_contract_bidunlist_tokenid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidunlist",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
