# Generated by Django 4.1.3 on 2023-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_bidunlist_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
            ],
        ),
    ]
