# Generated by Django 4.1.3 on 2023-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_featuredcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bids",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bids",
            name="userAddress",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="bidunlist",
            name="image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bidunlist",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bidunlist",
            name="userAddress",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255
            ),
        ),
    ]
