# Generated by Django 4.1.3 on 2023-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_bids_viewed_bidunlist_viewed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("viewed", models.BooleanField(default=False)),
                (
                    "image",
                    models.CharField(
                        default="https://cdn.pixabay.com/photo/2013/07/12/14/32/bell-148428_1280.png",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
