# Generated by Django 4.1.3 on 2023-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="expiring",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="items",
            name="minting",
            field=models.IntegerField(default=1),
        ),
    ]
