# Generated by Django 4.1.3 on 2023-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_items_expiring_items_minting"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="notifications",
            name="userAddress",
            field=models.CharField(
                default="0x000000000000000000000000000000", max_length=255
            ),
        ),
    ]
