# Generated by Django 4.1.3 on 2023-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_notifications_amount_notifications_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="link",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
