# Generated by Django 4.1.3 on 2023-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0002_netuser_my_refral"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="screen_shot",
            field=models.CharField(default="no ss", max_length=255),
        ),
    ]
