# Generated by Django 4.1.3 on 2023-06-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0003_deposit_screen_shot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="ending_date",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="starting_date",
        ),
        migrations.AddField(
            model_name="trade",
            name="time_span",
            field=models.FloatField(default=6),
        ),
    ]
