# Generated by Django 4.1.3 on 2023-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "networking",
            "0004_remove_trade_ending_date_remove_trade_starting_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ending_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="starting_time",
            field=models.FloatField(default=0),
        ),
    ]
