# Generated by Django 4.1.3 on 2023-07-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0006_alter_order_ending_time_alter_order_starting_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ending_time",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="starting_time",
            field=models.FloatField(),
        ),
    ]
