# Generated by Django 4.1.3 on 2023-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0007_alter_order_ending_time_alter_order_starting_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="currency",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
