# Generated by Django 4.1.3 on 2023-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0008_deposit_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="tx_hash",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
