# Generated by Django 4.1.3 on 2023-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0010_order_level_1_order_level_2_order_level_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="disable",
            field=models.BooleanField(default=False),
        ),
    ]
