# Generated by Django 4.1.3 on 2023-07-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0012_netuser_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netuser",
            name="wallet",
        ),
    ]
