# Generated by Django 4.1.3 on 2023-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0013_remove_netuser_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="netuser",
            name="wallet",
            field=models.CharField(default="0x0000", max_length=255),
        ),
    ]
