from django.urls import path
from .views import *
urlpatterns = [
 path('' ,homepage, name='home' ),
 path('allItems/' ,allItems, name='allItems' ),
 path('user/<str:cat>/' ,Adduser, name='user' ),
 path('itemids/' ,itemids, name='ids' ),
 path('bid/' ,getBids, name='bids' ),
 path('onsale/' ,allItemsbyaddress, name='onsale' ),
 path('auctions/' ,allItemsauction, name='onsale' ),
 path('delete/' ,DeleteItems, name='onsales' ),
 path('license/' ,allItemslicense, name='onsale' ),
 path('create_get_collection/' ,collections, name='onsale1' ),
 path('all_collections/' ,Allcollections, name='onsale2' ),
 path('all_collections_by_user/<str:user>/' ,collections_by_user, name='onsale4' ),
 path('all_collection_by_user/<str:user>/' ,collection_by_user, name='onsale5' ),
 path('all_routes/' , Preview, name='onsale2' ),
 path("all_users/",All_users),
 path("share/",user),
#  singlecollection
 path('collection/<int:pk>/' , singlecollection, name='single_collection' ),
 path('singleuser/<str:user>/',singleuser),
 path('onsale/<str:contract>/<int:ItemId>' ,Onsale, name='onsale3' ),
#  allItQuestions allILicense
 path('questions/' ,allItQuestions, name='allItQuestions' ),
 path('licenses/' ,allILicense ),
 path('sell/<str:toke>/<int:itemid>/' ,SolidItem ),
 path('question/<int:pk>/' ,Question1, name='Question1' ),
 path('reward/<str:pk>/' ,RewardView, name='Question2' ),
 path('location/' ,Locations, name='Question2' ),
 path('base_fee/' ,BaseFees, name='BaseFees' ),
 path('block/<int:pk>/<str:objType>/' ,Ban, name='BaseFes1' ),
 path('link/<str:pk>/' ,collectionLink, name='collectionLink' ),
 path('blogs/' ,Blogs, name='all_blogs' ),
 path('blog/<int:pk>/' ,Blog, name='blog' ),
 path('close_bid/<int:pk>/' ,CloseBid, name='bido' ),
 path('create_bid/' ,MakeBid, name='bidd' ),
 path('getfc/' ,GetFeaturedCollection, name='getfc' ),
 path('get_bids/<str:contract>/<int:tokenid>/' ,GetBids, name='bidd' ),
 path('notifications/<str:user>/' ,allNotifications, name='allNotifications' ),
 path('history/<str:user>/' ,NotificationHistory, name='allNotificationHistory' ),
 path('view/<int:pk>/' ,viewNotification, name='allNotificationHistory' ),
 path('all_sales/' ,Allsales, name='Allsales' ),
 path('all_auctions/' ,AllAuctions, name='all_auctions' ),
 path('all_aution_bids/' ,BidsAuctions, name='all_bids' ),
]